package com.alzheimer.models;
// Generated 29-jun-2019 21:11:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consultas generated by hbm2java
 */
@Entity
@Table(name="consultas"
    ,catalog="alzheimerdb"
)
public class Consultas extends Model<Consultas> implements java.io.Serializable {


     private Integer id;
     private Pacientes pacientes;
     private Usuarios usuarios;
     private Date fecha;
     private Set exameneses = new HashSet(0);

    public Consultas() {
    }

	
    public Consultas(Pacientes pacientes, Usuarios usuarios, Date fecha) {
        this.pacientes = pacientes;
        this.usuarios = usuarios;
        this.fecha = fecha;
    }
    /*public Consultas(Pacientes pacientes, Usuarios usuarios, Date fecha, Set exameneses) {
       this.pacientes = pacientes;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.exameneses = exameneses;
    }*/
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="paciente_id", nullable=false)
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

/*@OneToMany(fetch=FetchType.LAZY, mappedBy="consultas")
    public Set getExameneses() {
        return this.exameneses;
    }
    
    public void setExameneses(Set exameneses) {
        this.exameneses = exameneses;
    }
*/

    @Override
    public String toString() {
        return "Consultas{" + "id=" + id + ", pacientes=" + pacientes + ", usuarios=" + usuarios + ", fecha=" + fecha + ", exameneses=" + exameneses + '}';
    }

}


