package com.alzheimer.models;
// Generated 29-jun-2019 21:11:18 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examenes generated by hbm2java
 */
@Entity
@Table(name="examenes"
    ,catalog="alzheimerdb"
)
public class Examenes extends Model<Examenes> implements java.io.Serializable {


     private Integer id;
     private Consultas consultas;
     private Date fecha;
     private Date horaInicio;
     private Date horaFinal;
     private int totalAciertos;
     private int totalErrores;

    public Examenes() {
    }

    public Examenes(Consultas consultas, Date fecha, Date horaInicio, Date horaFinal, int totalAciertos, int totalErrores) {
       this.consultas = consultas;
       this.fecha = fecha;
       this.horaInicio = horaInicio;
       this.horaFinal = horaFinal;
       this.totalAciertos = totalAciertos;
       this.totalErrores = totalErrores;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consulta_id", nullable=false)
    public Consultas getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Consultas consultas) {
        this.consultas = consultas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora_inicio", nullable=false, length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora_final", nullable=false, length=8)
    public Date getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(Date horaFinal) {
        this.horaFinal = horaFinal;
    }

    
    @Column(name="total_aciertos", nullable=false)
    public int getTotalAciertos() {
        return this.totalAciertos;
    }
    
    public void setTotalAciertos(int totalAciertos) {
        this.totalAciertos = totalAciertos;
    }

    
    @Column(name="total_errores", nullable=false)
    public int getTotalErrores() {
        return this.totalErrores;
    }
    
    public void setTotalErrores(int totalErrores) {
        this.totalErrores = totalErrores;
    }




}


