package com.alzheimer.models;
// Generated 29-jun-2019 21:11:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImagenesId generated by hbm2java
 */
@Embeddable
public class ImagenesId  implements java.io.Serializable {


     private int parentescoId;
     private int pacienteId;

    public ImagenesId() {
    }

    public ImagenesId(int parentescoId, int pacienteId) {
       this.parentescoId = parentescoId;
       this.pacienteId = pacienteId;
    }
   


    @Column(name="parentesco_id", nullable=false)
    public int getParentescoId() {
        return this.parentescoId;
    }
    
    public void setParentescoId(int parentescoId) {
        this.parentescoId = parentescoId;
    }


    @Column(name="paciente_id", nullable=false)
    public int getPacienteId() {
        return this.pacienteId;
    }
    
    public void setPacienteId(int pacienteId) {
        this.pacienteId = pacienteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImagenesId) ) return false;
		 ImagenesId castOther = ( ImagenesId ) other; 
         
		 return (this.getParentescoId()==castOther.getParentescoId())
 && (this.getPacienteId()==castOther.getPacienteId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getParentescoId();
         result = 37 * result + this.getPacienteId();
         return result;
   }   


}


