package com.alzheimer.models;
// Generated 29-jun-2019 21:11:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Imagenes generated by hbm2java
 */
@Entity
@Table(name="imagenes"
    ,catalog="alzheimerdb"
)
public class Imagenes extends Modelo<Imagenes>  implements java.io.Serializable {


     private Integer id;
     private Pacientes pacientes;
     private String parentesco;
     private String directorio;
     private String descripcion;

    public Imagenes() {
    }

    public Imagenes(Integer id, Pacientes pacientes, String parentesco, String directorio, String descripcion) {
       this.id = id;
       this.pacientes = pacientes;
       this.parentesco = parentesco;
       this.directorio = directorio;
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="paciente_id", nullable=false, insertable=false, updatable=false)
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }

    @Column(name="parentesco", nullable=false)
    public String getParentescos() {
        return this.parentesco;
    }
    
    public void setParentescos(String parentesco) {
        this.parentesco = parentesco;
    }

    
    @Column(name="directorio", nullable=false)
    public String getDirectorio() {
        return this.directorio;
    }
    
    public void setDirectorio(String directorio) {
        this.directorio = directorio;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


