/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alzheimer;

import com.alzheimer.models.Roles;
import com.alzheimer.models.Usuarios;
import com.alzheimer.utilities.SessionFactoryHelper;
import java.awt.EventQueue;
import java.util.Date;
import java.util.List;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.query.Query;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

/**
 *
 * @author aldebaran
 */
@SpringBootApplication
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        Inicializador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspContenedor = new javax.swing.JScrollPane();
        jmbMenuOpciones = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiInicio = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmMedicos = new javax.swing.JMenu();
        jmiMedicosRegistro = new javax.swing.JMenuItem();
        jmPacientes = new javax.swing.JMenu();
        jmiPacienteRegistro = new javax.swing.JMenuItem();
        jmiHistoricos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alzheimer");
        setResizable(false);

        jmArchivo.setText("Archivo");

        jmiInicio.setText("Inicio");
        jmiInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiInicioMouseClicked(evt);
            }
        });
        jmArchivo.add(jmiInicio);

        jmiSalir.setText("Salir");
        jmiSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jmiSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiSalirMouseClicked(evt);
            }
        });
        jmArchivo.add(jmiSalir);

        jmbMenuOpciones.add(jmArchivo);

        jmMedicos.setText("Medicos");

        jmiMedicosRegistro.setText("Registro");
        jmMedicos.add(jmiMedicosRegistro);

        jmbMenuOpciones.add(jmMedicos);

        jmPacientes.setText("Pacientes");

        jmiPacienteRegistro.setText("Registro");
        jmPacientes.add(jmiPacienteRegistro);

        jmiHistoricos.setText("Historicos");
        jmPacientes.add(jmiHistoricos);

        jmbMenuOpciones.add(jmPacientes);

        setJMenuBar(jmbMenuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // <editor-fold defaultstate="collapsed" desc="Eventos"> 
    private void jmiSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiSalirMouseClicked
        
    }//GEN-LAST:event_jmiSalirMouseClicked

    private void jmiInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiInicioMouseClicked
        
    }//GEN-LAST:event_jmiInicioMouseClicked
    //</editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Métodos">
    private void Inicializador(){
        Session session = null;
        Transaction transaction = null;
        try{
            session = SessionFactoryHelper.getSessionFactory().openSession();
            /*transaction = session.beginTransaction();
            //transaction.begin();
            
            Usuarios usuario = new Usuarios();
            usuario.setNombres("Luis Jose 2");
            usuario.setApellidoPaterno("Padilla 2");
            usuario.setApellidoMaterno("Benitez 2");
            usuario.setFechaNacimiento(new Date());
            usuario.setSexo((short)0);
            usuario.setRoles(new Roles(){{
                this.setId(1);
                this.setNombre("administrador");
                this.setDescripcion("rol de administrador todos los privilegios.");
            }});
            session.save(usuario);
            
            transaction.commit();*/
            
            Query query = session.createQuery("from Usuarios");
            List<Usuarios> list = query.list();
            list.forEach(System.out::println);
        }catch(Exception ex){
            if(transaction != null){
                transaction.rollback();
            }
        }finally{
            if(session != null){
                session.close();
            }
        }
    }
    // </editor-fold> 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        ConfigurableApplicationContext context;
        context = new SpringApplicationBuilder(Application.class).headless(false).run(args);

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            Application windowApp = context.getBean(Application.class);
            windowApp.setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenu jmMedicos;
    private javax.swing.JMenu jmPacientes;
    private javax.swing.JMenuBar jmbMenuOpciones;
    private javax.swing.JMenuItem jmiHistoricos;
    private javax.swing.JMenuItem jmiInicio;
    private javax.swing.JMenuItem jmiMedicosRegistro;
    private javax.swing.JMenuItem jmiPacienteRegistro;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JScrollPane jspContenedor;
    // End of variables declaration//GEN-END:variables

}
